# Generated by Django 4.2.3 on 2023-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='blog_images/%Y/%m/%d/'),
        ),
    ]
