# Generated by Django 4.2.3 on 2023-07-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_status_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
