# Generated by Django 4.2.3 on 2023-07-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('cd', 'canceled'), ('pg', 'processing'), ('pd', 'posted')], default='pg', max_length=2),
        ),
    ]
