# Generated by Django 4.2.3 on 2023-07-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_author_user_alter_comment_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('set_post_status', 'Can set the status of the post to either publish or not')]},
        ),
    ]
